version: 0.2

phases:
  pre_build:
    commands:
      - echo Creating blank scm-source.json
      - touch scm-source.json
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t artifactory.acorn.cirrostratus.org/cypress/kube-deploy-cleaner .
      - docker tag artifactory.acorn.cirrostratus.org/cypress/kube-deploy-cleaner
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push artifactory.acorn.cirrostratus.org/cypress/kube-deploy-cleaner