apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-deploy-cleaner
  labels:
    application: kube-deploy-cleaner
    version: "0.1"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: kube-deploy-cleaner
            version: "0.1"
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cleaner
            image: "stevenacoffman/kube-deploy-cleaner:ea25c52"
            resources:
              limits:
                cpu: 200m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
